// Registers the service worker generated by scripts/generate-sw.ts.
// Dev builds have no service worker, so registration is production only.
export function registerServiceWorker() {
  if (!import.meta.env.PROD || !("serviceWorker" in navigator)) return;

  navigator.serviceWorker.register("/sw.js").catch((error: unknown) => {
    console.error("Service worker registration failed:", error);
  });
}
